### PR TITLE
Set up test producers/consumer

### PR DESCRIPTION
**Pull request by mjsway**
# Overview

## Task

Set up two test producers (one which produces a constant stream of messages and one which produces a batch of several thousand messages and then disconnects) as well as a test consumer to consume those messages. This allows the generation of messages in the background while running the application for testing purposes.

- [ ] Bug
- [x] Feature

## Description
Created a consumer, producer, and massProducer from the old `test.js` test producer/consumer, refactoring all to Typescript.

## Ticket

[**Trello**](https://trello.com/c/YbRaaHf0/28-write-demo-producer-consumer-to-stress-test-the-demo-cluster)

## Feature Validation / Bug Reproduction Steps

1. `npm run demo-cluster`; give the cluster a minute to spin up.
2. Navigate to `localhost:3000` and log into Grafana using the credentials in the `docker-compose-cluster.yml`
3. Navigate to `localhost:5175/cluster` to view the Kafka Sonar front end.
4. In VSCode, open 3 terminals side-by-side. In one terminal, run `npm run demo-cluster-produce`, in one run `npm run demo-cluster-consume`, and in the final run `npm run demo-cluster-produce-mass` to run all three KafkaJS clients. (The clients can be run in parallel). As messages are produced, they should dynamically log in the terminal running the consumer. The terminal running the producer also logs its messages to the console, but the mass producer does not in order to facilitate repeated runs without having to kill it and restart it manually.
5. From the Kafka Sonar front end, observe the metrics in the cluster under Broker I/O update in real-time. **Note: these metrics will only be visible if you have the (still WIP) Grafana dashboards on your local machine, which are not included in the repo as of this PR. I believe most of you already do, but if not just send me a message and I'll send them to you.** 

## Previous Behavior
The producer/consumer were run out of one file. The producer produced one message and disconnected, and then the consumer consumed it and disconnected, making it difficult to produce large volumes of messages for stress testing the cluster and/or populating the cluster for testing purposes.

## Expected Behavior
The producer and consumer have been separated, and two different producers have been written. Now a constant stream of messages can be produced to the cluster with the ability to easily manufacture a massive influx of messages by running the mass producer one or more times in a row.

## Screenshots & Videos
Screen Shot 2023-07-08 at 11 47 11 PM
Messages in per sec should spike shortly after running the mass producer. As long as the terminal running the normal producer is not killed, these metrics should not drop to zero.
Screen Shot 2023-07-08 at 11 50 18 PM
In the Grafana search bar -> Kafka Topics / Logs, set the topic to test-topic and you should observe the total log size increasing over time.

### CODE REVIEW

**Comment by unatarajan** [comment]
@mjsway Excellent work here, and thank you for the explanations about steps to reproduce.

About the Grafana dashboards, I'm not certain what you mean by we need them on our local machines. Per our discussion yesterday, I tried commenting out `demo-cluster/configs/grafana` from the `.gitignore` file and then composing up the containers. When I logged into Grafana through the Docker link to localhost:3000, I couldn't see the project dashboards. The FE iframes also say the various Grafana panels / metrics / time series are not available. Lmk if I'm missing something here.

**Comment by mjsway** [comment]
@unatarajan Just to clarify, does your demo-cluster directory look like this?
Screen Shot 2023-07-10 at 8 51 30 AM
These are the files I meant when I said you need them on your local machine because we haven't PR'd them into the repo yet as they're still in development. Without these, Grafana does't know what to do with the metrics we expose to it via Prometheus.

**Comment by unatarajan** [comment]
@mjsway Thanks for clarifying! Makes sense now - my `demo-cluster/configs/grafana` subdirectories are empty. If you can share the files, I will re-test.

**Comment by mjsway** [comment]
@unatarajan Done! Check Slack.

**Review by unatarajan — APPROVED** [review]
I see the expected production / mass production / consumption when running the cluster without Cypress.

I also ran the cluster with the Cypress container up. The existing FE test passes and the cypress container exits, as expected (I checked the cypress container Docker log and the video artifact of the test run). Production and consumption are not affected by cypress running, still seeing expected behavior per metrics rendering on FE of the application. Screenshot included to confirm my test.

Approving this PR!

Screenshot 2023-07-10 at 4 06 08 PM

**Review by stekim4 — APPROVED** [review]
Approved.

**Pull request merged**
